CREATE TABLE USER_AGENT3
(
ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
CONFIRMPASSWORD VARCHAR(50) NOT NULL,
CONTACTDETAILS VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
AMOUNT NUMBER(11) NOT NULL
);

CREATE TABLE ADMIN2
(
ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
USER_NAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
CONFIRMPASSWORD VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
CONTACTDETAILS VARCHAR(50) NOT NULL
);

CREATE TABLE BEAUTY_PRODUCTS
(
ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(500) NOT NULL,
INGREDIENTS VARCHAR(500) NOT NULL,
INGREDIENTS_ID NUMBER(11),
FOREIGN KEY(INGREDIENTS_ID)
REFERENCES INGREDIENTS(ID)
);

CREATE TABLE INGREDIENTS
(
ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(500) NOT NULL,
ISSUES_TARGETED VARCHAR(255) NOT NULL,
SKIN_TYPE VARCHAR(255) NOT NULL,
SKIN_ID NUMBER(11),
FOREIGN KEY(SKIN_ID)
REFERENCES SKIN_TYPE(ID),
ID_ISSUES NUMBER(25),
FOREIGN KEY(ID_ISSUES)
REFERENCES ISSUE(ID),
HAIR_TYPE NUMBER(11),
FOREIGN KEY(HAIR_TYPEID)
REFERENCES HAIR_TYPE(ID)
);

CREATE TABLE ISSUE
(
ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

CREATE TABLE SKIN_TYPE
(
ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

CREATE TABLE HAIR_TYPE
(
ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

CREATE TABLE BILLAMOUNT
(
USERNAME VARCHAR(50) NOT NULL,
CUSTOMER_ID NUMBER(11) NOT NULL,
PRODUCT VARCHAR(500) NOT NULL,
QUANTITY NUMBER(11) NOT NULL,
PRICE NUMBER(11) NOT NULL
);